# Fiftyone data augmentation and splitting
fiftyone:
  dataset_name: "sta-toyota-prius-5dr-hatchback-auto-d2-test-2"
  augment:
    data_path: "./datasets/test-dataset/images"
    labels_path: "./datasets/test-dataset/result.json"
  export:
    label_field: "segmentations"
    output_dir: "./export"

# Model prediction and training
train:
  base_model_path: "yolov8n-seg.pt"
  dataset: "./dataset/dataset.yaml"
  params:
    imgsz: 640
    epochs: 100
    batch: 32
    conf: 0.3

predict:
  vehicle_model_path: "./models/best/weights/best.pt"
  lamp_model_path: ""
  source: "video.mp4"
  output_dir: "./output-predict"
  params:
    conf: 0.3
