# Fiftyone data augmentation and splitting
dataset:
  data_path: "./datasets/test-dataset/images"
  labels_path: "./datasets/test-dataset/result.json"
  name: "sta-toyota-prius-5dr-hatchback-auto-d2-test-2"
  classes: ["TOYOTA"]
  label_field: "segmentations"
  export_dir: "./output"

# Model prediction and training
model:
  # Pre-trained weights (e.g ./model/weights/best.pt)
  path: "./models/best/weights/best.pt"
  # For training (e.g. ./dataset/dataset.yaml)
  source: "./dataset/dataset.yaml"
  params:
    imgsz: 640
    epochs: 100
    batch: 32
    conf: 0.3

