# Fiftyone data augmentation and splitting
fiftyone:
  dataset_name: "pre-aug"
  augment:
    data_path: "./datasets/pre-aug/images"
    labels_path: "./datasets/pre-aug/result.json"
  export:
    label_field: "segmentations"
    output_dir: "./export"

# Model prediction and training
train:
  base_model_path: "yolov8n-seg.pt"
  dataset: "./dataset/dataset.yaml"
  params:
    imgsz: 640
    epochs: 100
    batch: 32
    conf: 0.3

predict:
  vehicle_model_path: "./models/vehicle/weights/best.pt"
  lamp_model_path: "./models/lamp-v2/weights/best.pt"
  # source: "/mnt/sta/test/20240502_Front_D2_PRIUS-5DR-HATCHBACK.mp4"
  source: "/mnt/c/Users/UVSS/AppData/Local/CapCut/Videos/track_test6.mp4"
  output_dir: "./output-predict"
  params:
    conf: 0.5
    ref_pt:
      x: 1400 
      y: 700