# Fiftyone images augmentation and splitting
fiftyone:
  dataset_name: "Test"
  augment:
    data_path: "Path_To_Your_Repository\\UVSM\\Your_Dataset_Names\\images"
    labels_path: "Path_To_Your_Repository\\UVSM\\Your_Dataset_Names\\result.json"
  export:
    label_field: "segmentations"
    output_dir: "./Export_Directory_Name"

# Model prediction and training
train:
  base_model_path: "yolov8n-seg.pt"
  dataset: "Path_To_Your_Dataset"
  params:
    imgsz: 640
    epochs: 100
    batch: 32
    conf: 0.3
    patience: 5

heatmap:
  model_path : "Path_To_Your_Model"
  image_path : "Path_To_Your_Images"
